In [204]:
import os
import re
import aocd
import string
import numpy as np
import pandas as pd
from copy import deepcopy
from aocd import submit


data = aocd.get_data(day=19, year=2016).split('\n')[0]
data = int(data)
#data = 5

current_day is only available in December (EST)


In [4]:
# if the total number of elves is even,
# every even number one is removed
# if the total number of elves is odd, every even numbered elf is removed and then the first elf is also removed

In [28]:
elves_list = list(range(1,data+1))
elves_list[1::2]

[2, 4]

In [31]:
elves_list = list(range(1,data+1))

while(len(elves_list) > 1):
    #print('\nBefore', elves_list)
    length = len(elves_list)
    if (length % 2) == 0:
        elves_list = elves_list[::2]
    else:
        elves_list = elves_list[::2][1:]
    #print('After',elves_list)

In [32]:
elves_list

[1842613]

In [50]:


def start_timer():
    global start_time
    start_time = pd.Timestamp.now()
    
def tick(msg=''):
    now = pd.Timestamp.now()
    print('  ', msg, now-start_time )
    
start_timer()
tick('a')

   a 0 days 00:00:00.000031


In [55]:
#part 2
data = 5
elves_list = list(range(1,data+1))
elfs_turn = 1
while(len(elves_list) > 1):
    start_timer()
    print('\nBefore', elves_list)
    length = len(elves_list)
    print(length, end='\r')
    elfs_position = elves_list.index(elfs_turn)
    tick(1)
    elf_opposite_position = (elfs_position + length // 2) % length
    tick(2)
    elves_list.remove(elves_list[elf_opposite_position])
    #elves_list = elves_list[:elf_opposite_position] + elves_list[elf_opposite_position+1:]
    
    tick(3)
    print('After',elves_list)


Before [1, 2, 3, 4, 5]
   1 0 days 00:00:00.000664
   2 0 days 00:00:00.000866
   3 0 days 00:00:00.000974
After [1, 2, 4, 5]

Before [1, 2, 4, 5]
   1 0 days 00:00:00.000058
   2 0 days 00:00:00.000166
   3 0 days 00:00:00.000352
After [1, 2, 5]

Before [1, 2, 5]
   1 0 days 00:00:00.000523
   2 0 days 00:00:00.000643
   3 0 days 00:00:00.000732
After [1, 5]

Before [1, 5]
   1 0 days 00:00:00.000170
   2 0 days 00:00:00.000255
   3 0 days 00:00:00.000451
After [1]


In [67]:

data = 5
elves_list = np.array(list(range(1,data+1)))

for _ in range(int(np.ceil(np.log(data)/np.log(2)))):
    i = 0
    while i < len(elves_list):
        print('\nBefore', elves_list)
        #print(length, end='\r')
        length = len(elves_list)
        elf_opposite_position = (i + length // 2) % length
        #del elves_list[elf_opposite_position]
        print('After',elves_list)
        i += 1
    if len(elves_list) == 1:
        break


Before [1, 2, 3, 4, 5]
After [1, 2, 4, 5]

Before [1, 2, 4, 5]
After [1, 2, 4]

Before [1, 2, 4]
After [2, 4]

Before [2, 4]
After [2]


In [120]:

#data = 
e = np.ones(data, dtype='bool')

for _ in range(int(np.ceil(np.log(data)/np.log(2)))):
    i = 0
    if len(e[e]) == 1:
        break
    while i < len(e[e]):
        #print('\nBefore', np.where(e)[0])
        #print(elves_list[elves_list !=0][i])
        print(length, end='\r')
        length = len(e[e])
        elf_opposite_position = (i + length // 2) % length
        #del 
        #print(elves_list[elves_list !=0][elf_opposite_position])
        elf_opposite_position = np.where(e)[0][elf_opposite_position]
        e[elf_opposite_position] = 0
        #print('After',np.where(e)[0])
        i += 1
    #print('_')
        

KeyboardInterrupt: 

In [113]:
data

5

True

In [ ]:
# takes from 1 + (length // 2)%length, 2 + ((length-1)//2)%2


In [206]:
data=12

elves_list = np.array(list(range(1,data+1)))
for _ in range(int(np.ceil(np.log(data)/np.log(2)))):
    
    remove = []
    length = len(elves_list)
    print(elves_list)
    for i in range(0,len(elves_list)//2):
        remove += [(i + (length - (i))//2 + (i))%length]
        print('remove indices',remove[-1])
    roll_to = elves_list[i]
    # reset to start from 0 again
    elves_list = np.delete(elves_list,remove)
    roll_to = np.where(elves_list == roll_to)[0][0] + 1
    
    print(elves_list, i, roll_to)
    elves_list = np.roll(elves_list, -roll_to)
    print(elves_list)
elves_list

[ 1  2  3  4  5  6  7  8  9 10 11 12]
remove indices 6
remove indices 7
remove indices 9
remove indices 10
remove indices 0
remove indices 1
[ 3  4  5  6  9 12] 5 4
[ 9 12  3  4  5  6]
[ 9 12  3  4  5  6]
remove indices 3
remove indices 4
remove indices 0
[12  3  6] 2 2
[ 6 12  3]
[ 6 12  3]
remove indices 1
[6 3] 0 1
[3 6]
[3 6]
remove indices 1
[3] 0 1
[3]


array([3])

In [143]:
np.roll(range(10), -(i+1))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [144]:
1006236

0