In [39]:
import os
import re
import aocd
import numpy as np
import pandas as pd
from aocd import submit
from tqdm import tqdm
from collections import Counter


#data = aocd.get_data(day=11, year=2021)#.split('\n')
data = """5665114554
4882665427
6185582113
7762852744
7255621841
8842753123
8225372176
7212865827
7758751157
1828544563""".split('\n')
test = """5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526""".split('\n')
#data = test
data = np.array([[int(y) for y in x] for x in data])

def get_adjacent(i,j, data):
    corners = []
    if i != 0:
        corners += [(i-1,j)]
    if( i != 0) & (j!=0):
        corners += [(i-1,j-1)]
    if( i != 0) & (j != (len(data[i]) - 1)):
        corners += [(i-1,j+1)]
    if( i != (len(data) - 1)) & (j!=0):
        corners += [(i+1,j-1)]
    if(i != (len(data) - 1)) & (j != (len(data[i]) - 1)):
        corners += [(i+1,j+1)]
    if j != 0:
        corners += [(i,j-1)]
    if i != (len(data) - 1):
        corners += [ (i+1,j) ]
    if j != (len(data[i]) - 1):
        corners += [(i,j+1)]
    return corners

n_steps = 1000

tot_flashed = 0
for step in range(1,n_steps+1):
    flashed = np.zeros(data.shape)
    data += 1
    next_flashed = np.zeros(data.shape)
    next_flashed[data >= 10] = 1
    while (next_flashed != flashed).any():
        _is, _js = np.where((next_flashed == 1)&(flashed == 0))
        for i, j in zip(list(_is),list(_js)):
            adj = get_adjacent(i,j,data)

            for ai, aj in adj:
                data[ai,aj] += 1
        
        flashed = next_flashed
        
        next_flashed = np.zeros(data.shape)
        next_flashed[data >= 10] = 1
        
    tot_flashed += next_flashed.sum()
    data[data >= 10] = 0
    
    if next_flashed.sum() == np.product(next_flashed.shape):
        print('Found when all flash', step)
    
data, flashed,tot_flashed

Found when all flash 258
Found when all flash 268
Found when all flash 278
Found when all flash 288
Found when all flash 298
Found when all flash 308
Found when all flash 318
Found when all flash 328
Found when all flash 338
Found when all flash 348
Found when all flash 358
Found when all flash 368
Found when all flash 378
Found when all flash 388
Found when all flash 398
Found when all flash 408
Found when all flash 418
Found when all flash 428
Found when all flash 438
Found when all flash 448
Found when all flash 458
Found when all flash 468
Found when all flash 478
Found when all flash 488
Found when all flash 498
Found when all flash 508
Found when all flash 518
Found when all flash 528
Found when all flash 538
Found when all flash 548
Found when all flash 558
Found when all flash 568
Found when all flash 578
Found when all flash 588
Found when all flash 598
Found when all flash 608
Found when all flash 618
Found when all flash 628
Found when all flash 638
Found when all flash 648


(array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 11426.0)

In [24]:
data[np.where(flashed == 1)] += 1
data

array([[ 2,  2,  2,  2,  2],
       [ 2, 11, 11, 11,  2],
       [ 2, 11,  2, 11,  2],
       [ 2, 11, 11, 11,  2],
       [ 2,  2,  2,  2,  2]])